name: Build and Publish Website

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm install && npm run build --base /db-workshop

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
          # fqdn: platformatic.dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
